n8willis/opentype-shaping-documents

opentype-shaping-bengali.md, opentype-shaping-devanagari.md, opentype-shaping-gujarati.md, opentype-shaping-gurmukhi.md, opentype-shaping-indic-general.md, opentype-shaping-kannada.md, opentype-shaping-malayalam.md, opentype-shaping-oriya.md, opentype-shaping-sinhala.md, opentype-shaping-tamil.md, opentype-shaping-telugu.md
Minor spelling fix for the clarifications made for issue #34. `reodered` -> `reordered`.
The new explanation reads well!
=> Indic all: Fix typo in adjacent marks description

opentype-shaping-gujarati.md
The Indic2 tag for Gujarati should be `<gjr2>`, not `<guj2>`.
[Gujarati OpenType doc (Appendix A)](https://docs.microsoft.com/en-us/typography/script-development/gujarati#appendix-a-writing-system-tags).
=> Indic: Indic2 tag for Gujarati should be `gjr2`

opentype-shaping-tamil.md
Add-on to issue #47.
Make final Reph positioning text consistent with other scripts that have the `REPH_POS_AFTER_POST` shaping characteristic.
=> Tamil: edit final Reph positioning text

opentype-shaping-bengali.md, opentype-shaping-devanagari.md, opentype-shaping-gujarati.md, opentype-shaping-gurmukhi.md, opentype-shaping-indic-general.md, opentype-shaping-kannada.md, opentype-shaping-malayalam.md, opentype-shaping-oriya.md, opentype-shaping-sinhala.md, opentype-shaping-tamil.md, opentype-shaping-telugu.md
This is a rough draft at revising the usage of "base consonant" in the spec to be inclusive — wherever necessary, but no further — of independent-vowel bases and "surrogate" base codepoints like placeholders and dotted circles.
When complete, this will be rolled out to other Indic / Brahmic script docs. For now it was more helpful to implement changes on one specific script, rather than on the more vaguely-worded Indic General.
=> Base clarification [WIP]

opentype-shaping-bengali.md, opentype-shaping-devanagari.md, opentype-shaping-gujarati.md, opentype-shaping-gurmukhi.md, opentype-shaping-indic-general.md, opentype-shaping-kannada.md, opentype-shaping-malayalam.md, opentype-shaping-oriya.md, opentype-shaping-sinhala.md, opentype-shaping-tamil.md, opentype-shaping-telugu.md
In-progress updates to final-"Reph" reordering. Currently Devanagari (REPH_POS_BEFORE_POST), Bengali (REPH_POS_AFTER_SUBJOINED), and Kannada (REPH_POS_BEFORE_POST).
[edit] Adding Gurmukhi (REPH_POS_BEFORE_SUBJOINED) and Malayalam (REPH_POS_AFTER_MAIN).
=> Expand final reph reordering algorithms

opentype-shaping-bengali.md, opentype-shaping-devanagari.md, opentype-shaping-gujarati.md, opentype-shaping-gurmukhi.md, opentype-shaping-kannada.md, opentype-shaping-malayalam.md, opentype-shaping-oriya.md, opentype-shaping-tamil.md, opentype-shaping-telugu.md
This PR incorporates two major fixes:
- It strengthens the base-finding algorithm by adding initial "Ra,Halant" (rather than "initial Ra") as the test and by specifying how to drop out of the base search when a ZWJ/ZWNJ is encountered
- It notes exceptions to final-reordering behavior needed for left-side matras in `mlm2` and `tml2`.
It also improves the formatting of early discussions where the effects of ZWJ/ZWNJ are mentioned in passing by pulling those effects into bulleted points, as is already done elsewhere to denote exceptions and special circumstances that implementations ought to heed.
These are meant to address matters raised in issues #68, #73, and #40. So if you have eyes on those issues, please have a look and flag anything for review that is problematic.
=> Improve base-algorithm ZWJ and pre-base ZWJ

opentype-shaping-hebrew.md
=> Minor typo fix in the Hebrew documentation

opentype-shaping-bengali.md, opentype-shaping-devanagari.md, opentype-shaping-gujarati.md, opentype-shaping-gurmukhi.md, opentype-shaping-indic-general.md, opentype-shaping-kannada.md, opentype-shaping-malayalam.md, opentype-shaping-oriya.md, opentype-shaping-sinhala.md, opentype-shaping-tamil.md, opentype-shaping-telugu.md
For Indic2. Move `NUMBER` into the _placeholder_ class used in syllable identification, and add a note to that effect in case anyone overlooks it. Puts us in line with HarfBuzz treatment and fixes #108.
=> Numeral as placeholders

opentype-shaping-bengali.md, opentype-shaping-devanagari.md, opentype-shaping-gujarati.md, opentype-shaping-gurmukhi.md, opentype-shaping-indic-general.md, opentype-shaping-kannada.md, opentype-shaping-malayalam.md, opentype-shaping-oriya.md, opentype-shaping-sinhala.md, opentype-shaping-tamil.md, opentype-shaping-telugu.md
This is a proposed fix for #73, to address the 4.2 left-matra-reordering situation when the last explicit Halant is there due to a ZWJ or (hypothetically) ZWNJ. Uniscribe diverges from the specification and HarfBuzz follows suit so as to preserve compatibility, although it's only a few scripts with documented test-cases.
=> WIP: Improve last-Halant ZW[N]J handling in 4.2

character-tables/character-tables-bengali.md, character-tables/character-tables-devanagari.md, character-tables/character-tables-gujarati.md, character-tables/character-tables-gurmukhi.md, character-tables/character-tables-kannada.md, character-tables/character-tables-malayalam.md, character-tables/character-tables-oriya.md, character-tables/character-tables-sinhala.md, character-tables/character-tables-tamil.md, character-tables/character-tables-telugu.md, opentype-shaping-bengali.md, opentype-shaping-default.md, opentype-shaping-devanagari.md, opentype-shaping-gujarati.md, opentype-shaping-gurmukhi.md, opentype-shaping-hangul.md, opentype-shaping-indic-general.md, opentype-shaping-kannada.md, opentype-shaping-malayalam.md, opentype-shaping-mongolian.md, opentype-shaping-oriya.md, opentype-shaping-sinhala.md, opentype-shaping-tamil.md, opentype-shaping-telugu.md
Contains sample clarifications regarding NBSP, ZWJ, and ZWNJ, and the term "standalone" syllable, as applied to syllable-identification, `half`, and `cjct`. As per #43. Eventually would be propagated to other Indic2-script docs.
=> [WIP] Standalone syllables, NBSP, and ZWJ polish

opentype-shaping-khmer.md
U+17D2 KHMER SIGN COENG has the shaping class `INVISIBLE_STACKER`, not `COENG`.
=> Khmer: correction to Sign Coeng regex classification.

opentype-shaping-bengali.md, opentype-shaping-devanagari.md, opentype-shaping-gujarati.md, opentype-shaping-gurmukhi.md, opentype-shaping-indic-general.md, opentype-shaping-kannada.md, opentype-shaping-malayalam.md, opentype-shaping-oriya.md, opentype-shaping-sinhala.md, opentype-shaping-tamil.md, opentype-shaping-telugu.md
This is an in-progress revision that discusses dotted-circle insertion openly, rather than leaving it as an implicit "figure it out" problem. Currently just limited to Indic2 model, and currently just expected to fix #76.
=> [WIP] Dotted-circle handling

opentype-shaping-arabic.md, opentype-shaping-mongolian.md, opentype-shaping-nko.md, opentype-shaping-syriac.md
Minor; adds new text about ZWJ/ZWNJ/CGJ that brings the Arabic-general model scripts into line with Indic2.
Could perhaps use some examples of ZWJ/ZWNJ interaction with backtrack/lookahead matching, but that will not hold up merging.
=> Add special-purpose codepoint explanations to Arabic-General scripts.

opentype-shaping-arabic-general.md, opentype-shaping-arabic.md, opentype-shaping-mongolian.md, opentype-shaping-nko.md, opentype-shaping-normalization.md, opentype-shaping-syriac.md
This moves the AMTRA transient-mark-reordering stage to early in the Arabic model, while hopefully maintaining the distinction between it and the NFD/NFC generic mark reordering.
=> Arabic early mark reorder [WIP]

character-tables/character-tables-arabic.md, character-tables/character-tables-kannada.md, character-tables/character-tables-mongolian.md, character-tables/character-tables-telugu.md, opentype-shaping-arabic.md, opentype-shaping-mongolian.md, opentype-shaping-telugu.md
This updates the character tables for the Arabic, Kannada, Mongolian, and Telugu docs to reflect additions in Unicode v 14, including new codepoints and the corresponding Indic Positional / Indic Syllabic / Arabic Shaping / general-UCD info. 
I believe these are the only scripts affected by the updated release. Please speak up if I have overlooked something.
Note that for Arabic there is an entirely new block (Extended-B) and some additional Joining Groups.
I don't believe that there were major changes to the info on existing codepoints (the delta charts seem to reflect mostly representative glyph updates ...) but that is worth a separate pass anyway; new codepoints are (at least) self-contained and not likely to break existing implementations.
Note also that this update should be …
=> Unicode 14 update

opentype-shaping-indic-general.md, opentype-shaping-sinhala.md
For #120. Initial commit updates sort-order for Reph. Still to come is an update for handling the ambiguity & Win7/Win10 differences.
=> [WIP] Sinhala: update Reph specification

notes/uniscribe-bug-compatibility.md, opentype-shaping-kannada.md
=> Kannada, Uniscribe: note on final double-Halant post-base reordering exception in Indic1

opentype-shaping-indic-general.md, opentype-shaping-sinhala.md, opentype-shaping-telugu.md
This updates the two Indic2 script docs that use `REPH_MODE_EXPLICIT`, in light of #81. Believed to be the correct behavior for Sinhala, but a little less clear for Telugu, considering that Telugu's explicit-Reph-request sequence is only used for old orthography.
Also patches in some related references in the Indic-General doc.
=> Handle standalone explicit reph

notes/uniscribe-bug-compatibility.md, opentype-shaping-bengali.md, opentype-shaping-devanagari.md, opentype-shaping-gujarati.md, opentype-shaping-gurmukhi.md, opentype-shaping-indic-general.md, opentype-shaping-kannada.md, opentype-shaping-malayalam.md, opentype-shaping-oriya.md, opentype-shaping-sinhala.md, opentype-shaping-tamil.md, opentype-shaping-telugu.md
This fixes #72, bringing the docs back up to the same regular expressions used by HarfBuzz.
The essence is that a "_Consonant_,Halant,ZWJ,_matra_" sequence should get a dotted circle inserted just before the matra. Previously, this was not done because testing indicated that Uniscribe also did not insert the dotted-circle. Subsequent testing by HarfBuzz maintainers, however, narrowed down the Uniscribe behavior to be limited to "_Consonant_,Halant,ZWJ,_Consonant_,Halant,ZWJ,_matra_" cases (that is, two explicit half forms, followed by a matra).
That situation is almost certainly a bug, and only of interest to shapers targeting rigorous equivalence with Uniscribe. The MS specifications do not permit that.
So, this PR updates the regular expressions to match the updated versions in HarfBuzz …
=> Indic2: update regexes to disallow matras after C,H,ZWJ

character-tables/character-tables-lao.md, character-tables/character-tables-thai.md
These were missing from the Thai and Lao pages. The Thai page notes several general-puncuaton marks often used for writing minority languages.
=> Thai/Lao: add missing Miscellaneous tables to char-table pages

notes/README.md, notes/emoji-implementation.md
This migrates the table and instructions from #150 into a file in the notes/ subdirectory. New info for that table (or for other tables, such as which GSUB lookup types are used, what ZWJ permutation are supported, etc etc) can now be added via PRs.
=> Add emoji-implementation data to notes.

character-tables/character-tables-arabic.md, character-tables/character-tables-devanagari.md, character-tables/character-tables-kannada.md, character-tables/character-tables-lao.md, opentype-shaping-arabic.md
These are the new bits from Unicode 15 for the scripts covered in these docs.
A couple of brand-new, mostly empty blocks. Not a lot total, though.
- On Arabic Extended C, my decidedly sub-novice grasp of Arabic suggests that the new codepoints, which are small-below-word notations, don't interact with shaping or with AMTRA mark handling. Similar, I'm assuming, to other word-annotation codepoints. If I'm wrong definitely let me know.
- On Devanagari Extended A, I found a lot less written that gives clues to handling, but the new codepoints all sound like they're used as full-size symbol characters, not letters and not participating in any way with syllable or cluster behavior.
Bit less clear on the Lao addition; HarfBuzz source has it classified as a syllable-modifier, which wasn't a …
=> Unicode 15 additions

character-tables/character-tables-arabic.md, character-tables/character-tables-myanmar.md, opentype-shaping-arabic.md, opentype-shaping-myanmar.md
Updates to character tables and minor text corrections for Arabic and Myanmar. There may also be some additional updates in Unicode 16 in emoji sequence handling; if so, those will be addressed separately.
=> Update Arabic and Myanmar for Unicode16
